const fs = require('fs')
const path = require('path')

const jsDir = path.resolve(__dirname, 'build', 'static', 'js')
const jsFiles = fs.readdirSync(jsDir)

// Find the JavaScript file generated by react-scripts (usually starts with 'main.')
const jsFile = jsFiles.find((file) => file.startsWith('main.'))

if (jsFile) {
  // Rename the file to a standardized name, e.g., 'bundle.js'
  fs.renameSync(path.join(jsDir, jsFile), path.join(jsDir, 'aichwp.js'))
}

const cssDir = path.resolve(__dirname, 'build', 'static', 'css')
const cssFiles = fs.readdirSync(cssDir)

// Find the JavaScript file generated by react-scripts (usually starts with 'main.')
const cssFile = cssFiles.find((file) => file.startsWith('main.'))

if (cssFile) {
  // Rename the file to a standardized name, e.g., 'bundle.js'
  fs.renameSync(path.join(cssDir, cssFile), path.join(cssDir, 'aichwp.css'))
}
